CREATE DATABASE FAMILYAPP;
USE FAMILYAPP;

CREATE TABLE FAMILY(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    FAMILYNAME VARCHAR(30) NOT NULL
);

CREATE TABLE USERS(
	ID INT NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(25) NOT NULL,
    PWD VARCHAR(25) NOT NULL,
    FULLNAME VARCHAR(100) DEFAULT '',
    DOB DATE NULL,
    RELATIONSHIP ENUM('FATHER', 'MOTHER', 'CHILD', '') DEFAULT '', 
    FID INT,
    PRIMARY KEY (ID),
	FOREIGN KEY (FID) REFERENCES FAMILY(ID)
);

INSERT INTO FAMILY(FAMILYNAME) VALUES('TheMomins');
INSERT INTO USERS(USERNAME, PWD, FID) VALUES('Abanggi Momin', 'abc123!@#', 1);
INSERT INTO USERS(USERNAME, PWD, FID) VALUES('balmy', 'qwerty123', 1);