# SCHEMAS
CREATE TABLE FAMILY(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    FAMILYNAME VARCHAR(30) NOT NULL
);

CREATE TABLE USERS(
	ID INT NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(25) NOT NULL,
    PWD VARCHAR(25) NOT NULL,
    FULLNAME VARCHAR(100) DEFAULT '',
    DOB DATE NULL,
    RELATIONSHIP ENUM('FATHER', 'MOTHER', 'CHILD', '') DEFAULT '', 
    FID INT,
    PRIMARY KEY (ID),
	FOREIGN KEY (FID) REFERENCES FAMILY(ID)
);

CREATE TABLE MESSAGE(
	ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    SENDER_ID INT NOT NULL,
    SENDER_NAME VARCHAR(25) NOT NULL,
    RECEPIENT_ID INT NOT NULL,
    RECEPIENT_NAME VARCHAR(25) NOT NULL,
    EMAIL VARCHAR(65) NOT NULL,
    SUB VARCHAR(50) NOT NULL,
    MSG TEXT NOT NULL,
    TSTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SENDER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (RECEPIENT_ID) REFERENCES USERS(ID)
);

# TEST DATA
INSERT INTO FAMILY(FAMILYNAME) VALUES('TheMomins');

INSERT INTO USERS(USERNAME, PWD, FID) VALUES('abanggi', 'abc123!@#', 1);
INSERT INTO USERS(USERNAME, PWD, FID) VALUES('balmy', 'qwe!@#', 1);

INSERT INTO FAMILY(FAMILYNAME) VALUES('MarakAngels');

INSERT INTO USERS(USERNAME, PWD, FID) VALUES('betju', 'abc123!@#', 2);
INSERT INTO USERS(USERNAME, PWD, FID) VALUES('richard09', 'abc678', 2);
INSERT INTO USERS(USERNAME, PWD, FID) VALUES('richell', 'ghi#12', 2);
